### PR TITLE
Replaces usage of deprecated merge with assign

### LINKED ISSUE #152: DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead
Here are the cases where merge is used instead of assign.

https://github.com/cibernox/ember-native-dom-helpers/blob/43e8daa5b755373bd4b657def5b890e076d01ee1/tests/helpers/start-app.js#L1

https://github.com/cibernox/ember-native-dom-helpers/blob/43e8daa5b755373bd4b657def5b890e076d01ee1/addon-test-support/key-event.js#L1

https://github.com/cibernox/ember-native-dom-helpers/blob/43e8daa5b755373bd4b657def5b890e076d01ee1/addon-test-support/fire-event.js#L1

### PR DESCRIPTION
**Pull request by SergeAstapov**
Closes #152

### CODE REVIEW

**Comment by SergeAstapov** [comment]
We don't use this addon directly in our app as it's not needed with new-ish versions of ember-cli-qunit as stated in readme.

However [ember-cli-page-object](https://github.com/san650/ember-cli-page-object/blob/master/guides/native-events.md) depends on it in order to provide native events and avoid jQuery usage.

Once this is merged, can we get new version bump?

**Comment by SergeAstapov** [comment]
@cibernox do you think this can be merged?

**Comment by cibernox** [comment]
Sorry for the delay, I missed this notification while on holidays and when I returned I declared backruptancy of github notifications. Merged.

I'll release a new version later

**Comment by cibernox** [comment]
Released.

**Comment by SergeAstapov** [comment]
Thank you @cibernox!

**Pull request merged**
