### PR TITLE
Fix isFocusable for contenteditable

### PR DESCRIPTION
**Pull request by ro0gr**
addresses #69 
noticed this issue while working on #100

### CODE REVIEW

**Comment by ro0gr** [comment]
>  we should also add a check for the existence of tabindex

@RuslanZavacky can you please explain what do you mean? AFAIK any `HTMLElement` has a `tabIndex` property. Do you mean that an element should not be focused if `tabIndex` is equal to -1?

**Comment by cibernox** [comment]
@ro0gr afaik, an item with tabindex -1 cannot be focused *with the TAB key*, but it can still be focused by other methods, so I think that the code is correct as it is.

**Comment by ro0gr** [comment]
sounds good

**Comment by cibernox** [comment]
Thanks!

**Comment by ro0gr** [comment]
@cibernox sorry I've forgot to notice in pr description:
there is a one minor issue with [focus test](https://github.com/cibernox/ember-native-dom-helpers/pull/103/files#diff-d184e378a9a538ce65908f5c941c6e28R31) it will fail if the browser window is not active(no focus) while this test is running

**Comment by cibernox** [comment]
Don't worry, that is expected. That's just how focus generally works in browsers. Using headless mode usually shields us from that.

**Pull request merged**
