### PR TITLE
Removes flag MODEL_FACTORY_INJECTIONS and improve ember syntax

### PR DESCRIPTION
**Pull request by villander**
Removing this flag due to warning and improve ember syntax/ES6

This flag is needless for project with ember-cli >= 2.13

https://emberjs.com/deprecations/v2.x/#toc_id-ember-metal-model_factory_injections

### CODE REVIEW

**Comment by cibernox** [comment]
@villander Thank you for the changes, although I personally prefer to stick with regular `function` unless there is a reason (binding `this`) that makes me use the arrow function.

Could you revert that part and leave the rest?

**Comment by villander** [comment]
Done! @cibernox

**Comment by villander** [comment]
@cibernox can we merge that?

**Comment by cibernox** [comment]
I've been moving between countries, but LGTM. 

Thanks!

**Comment by villander** [comment]
Thanks @cibernox It's an honor to contribute to this addon.

**Pull request merged**
