### PR TITLE
Allow the `context` received by find to be a CSS selector

### PR DESCRIPTION
**Pull request by czterystaczwarty**
Before it could only be an HTMLElement

### CODE REVIEW

**Comment by fivak** [comment]
👍

**Comment by cibernox** [comment]
@czterystaczwarty I'd rather leave it as is. Mainly because it doesn't make much sense as it you want to do `find(string, string)` you could just as well do `find(string + ' ' + string)`

**Comment by czterystaczwarty** [comment]
I understand.
Then what is the point `findAll(selector, context)`?
I hit upon this inconsistency when I went from Ember/jQuery test helpers in my project.
So maybe all the helper should accept only HTMLElement as selector context.

**Comment by cibernox** [comment]
I believe that is simply a mistake. I'll fix it.

**Comment by cibernox** [comment]
@czterystaczwarty `findAll` now only accepts HTMLElements as context #107

**Pull request closed without merging**
