### PR TITLE
only using an array for a file inputs 'files' property

### LINKED ISSUE #94: selectFiles Seems Broken in Chrome Canary
Given:

```javascript
  await selectFiles(
    '.some-selector',
    [
      new Blob(['test-test'], {
        name: 'foo.jpg',
        type: 'image/jpeg'
      }),
    ]
  );
```

I see the following error message in Chrome Canary (v62):

screen shot 2017-08-08 at 1 04 49 pm

### PR DESCRIPTION
**Pull request by webark**
No longer attempting to munge the 'immutable' FileList. Closes #94

### CODE REVIEW

**Comment by webark** [comment]
@jherdman see if this works better for you.

**Comment by jherdman** [comment]
Works!

**Comment by cibernox** [comment]
If `FileList` is immutable by step, I think this is good. I misread it before, I thought it was firefox and now chrome doing something wrong, and it's them being more compliant with the spec.

Is there any commonly used public-api in FileList that it's not identical in array that we should copycat?

**Comment by cibernox** [comment]
Either way, this is good.

**Comment by cibernox** [comment]
I've just realised that if you do a try/catch just to rethrow the error you could just as well remove the try/catch entirely. Can you PR just that?

**Comment by webark** [comment]
there's an "item" method that you can pass in an index and it returns the file at that index. We could recreate that method potentially.

**Comment by webark** [comment]
ohh.. ya. course.

**Pull request merged**
